[versions]
android_gradle_plugin = "8.10.0"
android_test_version = "1.7.0"
appcompat = "1.7.0"
arch_core_testing = "2.2.0"
coil3 = "3.3.0"
compose_activity = '1.10.1'
compose = '1.9.5'
compose_plugin = '1.10.1'
core_ktx = '1.16.0'
firebase_bom = "33.6.0"
googleplay_services = "4.4.4"
gradle_firebase_crashlytics = "3.0.6"
junit_ext = "1.3.0"
junit = "4.13.2"
koin = '4.1.1'
koin_compose = "4.1.0"
kotlin = '2.2.21'
kotlin_coroutines_test = '1.10.2'
kotlin_coroutines = '1.10.2'
kotlin_datetime = "0.6.1"
kotlinx_serialization = "1.9.0"
ktor = "3.4.0"
material = "1.12.0"
mockk = "1.14.5"
multiplatform-settings = "1.3.0"
sqldelight = "1.5.5"

[libraries]
android-test-runner = { module = "androidx.test:runner", version.ref = "android_test_version" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch_core_testing" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "android_gradle_plugin" }
gradle-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "gradle_firebase_crashlytics" }
gradle-googleplay-services = { module = "com.google.gms:google-services", version.ref = "googleplay_services" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit_ext" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin_compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin_coroutines_test" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin-coroutines-desktop = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin_coroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin_datetime" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-jvm = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }
sqldelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-ios = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }

[bundles]
instrumentedtest = ["android-test-runner", "junit-ext"]
unittest = ["kotlin-coroutines-test", "mockk", "junit", "kotlin-test"]

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose_plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqldelight" }
