name: Android CI

on:
  push:
    branches: 
      - main
      - dev
    paths-ignore:
      - '**.md'
      - 'media/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'media/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    
    - name: set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      env:
        MONSTER_COMPENDIUM_KEYSTORE_PASSWORD: ${{ secrets.MONSTER_COMPENDIUM_KEYSTORE_PASSWORD }}
      run: ./gradlew assembleRelease testReleaseUnitTest jvmTest -Pdev

    - name: Verify database migration
      run: ./scripts/sqldelight/verifyDatabaseMigration

    - name: Generate AAB
      env:
        MONSTER_COMPENDIUM_KEYSTORE_PASSWORD: ${{ secrets.MONSTER_COMPENDIUM_KEYSTORE_PASSWORD }}
      run: ./gradlew bundleRelease
      
    - name: Upload the test report
      if: failure()
      uses: actions/upload-artifact@v3.1.1
      with:
        name: TestReport
        path: |
          feature-monster-compendium/build/reports/tests
          data/build/reports/tests
          domain/build/reports/tests
          
    - name: Upload an APK
      uses: actions/upload-artifact@v3.1.1
      with:
        name: app-dev-release.apk
        path: app/build/outputs/apk/release/app-dev-release.apk
        
    - name: Upload an APK metadata JSON
      uses: actions/upload-artifact@v3.1.1
      with:
        name: output-metadata.json
        path: app/build/outputs/apk/release/output-metadata.json

    - name: Upload an AAB
      uses: actions/upload-artifact@v3.1.1
      with:
        name: app-release.aab
        path: app/build/outputs/bundle/release/app-release.aab
