name: Multiplatform Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'media/**'
      - 'content/**'

jobs:
  multiplatform-build:
    name: Android and MacOS Distribution
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          MONSTER_COMPENDIUM_KEYSTORE_PASSWORD: ${{ secrets.MONSTER_COMPENDIUM_KEYSTORE_PASSWORD }}
        run: ./gradlew jvmTest testReleaseUnitTest assembleRelease bundleRelease :app:packageDmg

      - name: Verify database migration
        run: chmod +x ./scripts/sqldelight/verifyDatabaseMigration && ./scripts/sqldelight/verifyDatabaseMigration

      - name: Upload the test report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: |
            feature-monster-compendium/build/reports/tests
            data/build/reports/tests
            domain/build/reports/tests

      - name: Upload Dmg
        uses: actions/upload-artifact@v4
        with:
          name: MonsterCompendium-dmg
          path: app/build/compose/binaries/main/dmg/*.dmg

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Upload APK metadata JSON
        uses: actions/upload-artifact@v4
        with:
          name: app-output-metadata-json
          path: app/build/outputs/apk/release/output-metadata.json

  android-dev-distribution:
    name: Android APK Dev Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Dev Apk
        env:
          MONSTER_COMPENDIUM_KEYSTORE_PASSWORD: ${{ secrets.MONSTER_COMPENDIUM_KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease -Pdev

      - name: Upload Dev APK
        uses: actions/upload-artifact@v4
        with:
          name: app-dev-release-apk
          path: app/build/outputs/apk/release/app-dev-release.apk

  ubuntu-desktop-distribution:
    name: Ubuntu Desktop Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:packageDeb

      - name: Upload Deb
        uses: actions/upload-artifact@v4
        with:
          name: MonsterCompendium-deb
          path: app/build/compose/binaries/main/deb/*.deb

  windows-desktop-distribution:
    name: Windows Desktop Distribution
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:packageMsi

      - name: Upload Msi
        uses: actions/upload-artifact@v4
        with:
          name: MonsterCompendium-msi
          path: app/build/compose/binaries/main/msi/*.msi
