name: Multiplatform PR

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'media/**'
      - 'content/**'

jobs:
  multiplatform-build:
    name: Multiplatform Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.5.0
    
    - name: set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: latest-stable

    - name: Build with Gradle
      run: ./gradlew testDebugUnitTest jvmTest assembleDebug :app:packageDmg linkDebugFrameworkIosSimulatorArm64

    - name: Verify database migration
      run: chmod +x ./scripts/sqldelight/verifyDatabaseMigration && ./scripts/sqldelight/verifyDatabaseMigration

    - name: Build iOS
      run: xcodebuild build -configuration Debug -project ./iosApp/MonsterCompendium.xcodeproj -scheme MonsterCompendium -destination "platform=iOS Simulator,name=iPhone 14,OS=17.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Upload the test report
      if: failure()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: TestReport
        path: |
          feature-monster-compendium/build/reports/tests
          data/build/reports/tests
          domain/build/reports/tests

    - name: Upload Dmg
      uses: actions/upload-artifact@v4.6.2
      with:
        name: MonsterCompendium-dmg
        path: app/build/compose/binaries/main/dmg/*.dmg
          
    - name: Upload an APK
      uses: actions/upload-artifact@v4.6.2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload an APK metadata JSON
      uses: actions/upload-artifact@v4.6.2
      with:
        name: app-output-metadata-json
        path: app/build/outputs/apk/debug/output-metadata.json

  linux-desktop-distribution:
    name: Linux Desktop Distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:packageDeb :app:packageRpm

      - name: Upload Deb
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MonsterCompendium-deb
          path: app/build/compose/binaries/main/deb/*.deb

      - name: Upload Rpm
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MonsterCompendium-rpm
          path: app/build/compose/binaries/main/rpm/*.rpm

  windows-desktop-distribution:
    name: Windows Desktop Distribution
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.5.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:packageMsi

      - name: Upload Msi
        uses: actions/upload-artifact@v4.6.2
        with:
          name: MonsterCompendium-msi
          path: app/build/compose/binaries/main/msi/*.msi
